name: foodee_app
description: "Food Base Sample APp"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/image/

  fonts:
    - family: Unbounded
      fonts:
        - asset: assets/fonts/Unbounded-Light.ttf
        - asset: assets/fonts/Unbounded-Regular.ttf

